#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
ANCHOR_WORK_DIR=${ANCHOR_WORK_DIR:-/tmp/usdb-profile-anchor-boundary-e2e}
BTC_ANCHOR_MAX_AGE_BLOCKS=${BTC_ANCHOR_MAX_AGE_BLOCKS:-3}
ANCHOR_BOUNDARY_OBSERVE_SECONDS=${ANCHOR_BOUNDARY_OBSERVE_SECONDS:-4}

echo "[usdb-profile-anchor] Running BTC anchor max-age and USDB branch boundary E2E"
env \
  WORK_DIR="$ANCHOR_WORK_DIR" \
  BTC_ANCHOR_MAX_AGE_BLOCKS="$BTC_ANCHOR_MAX_AGE_BLOCKS" \
  ANCHOR_BOUNDARY_CHECK=1 \
  ANCHOR_BOUNDARY_OBSERVE_SECONDS="$ANCHOR_BOUNDARY_OBSERVE_SECONDS" \
  TARGET_BLOCKS=1 \
  BTC_RPC_PORT="${BTC_RPC_PORT:-28232}" \
  BTC_P2P_PORT="${BTC_P2P_PORT:-28233}" \
  BH_RPC_PORT="${BH_RPC_PORT:-28210}" \
  USDB_INDEXER_RPC_PORT="${USDB_INDEXER_RPC_PORT:-28220}" \
  ORD_RPC_PORT="${ORD_RPC_PORT:-28230}" \
  HTTP_PORT="${HTTP_PORT:-19745}" \
  P2P_PORT="${P2P_PORT:-31513}" \
  AUTHRPC_PORT="${AUTHRPC_PORT:-19751}" \
  VALIDATOR_HTTP_PORT="${VALIDATOR_HTTP_PORT:-19746}" \
  VALIDATOR_P2P_PORT="${VALIDATOR_P2P_PORT:-31514}" \
  VALIDATOR_AUTHRPC_PORT="${VALIDATOR_AUTHRPC_PORT:-19752}" \
  WALLET_NAME="${WALLET_NAME:-usdbanchor}" \
  ORD_WALLET_NAME="${ORD_WALLET_NAME:-ord-usdb-anchor-a}" \
  ORD_WALLET_NAME_B="${ORD_WALLET_NAME_B:-ord-usdb-anchor-b}" \
  "$ROOT_DIR/scripts/usdb/run_usdb_profile_e2e.sh"
