package usdb

import (
	_ "embed"
	"encoding/json"
	"testing"
)

// Generated by the real Rust indexer query matrix and checked against its per-block model.
//
//go:embed testdata/miner_pass_upgrade_queries.json
var minerPassUpgradeVectors []byte

type upgradeBreakdown struct {
	ExternalState EconomicExternalState `json:"external_state"`
	Aggregate     string                `json:"aggregate_collab_contribution"`
	Items         []struct {
		Raw          string `json:"collab_raw_energy"`
		Contribution string `json:"collab_contribution"`
		Weight       uint64 `json:"collab_weight_bps"`
	} `json:"items"`
}
type upgradeVectors struct {
	Schema     string                    `json:"schema_version"`
	Registry   btcActivationRegistry     `json:"registry"`
	Profiles   []PassEconomicProfileView `json:"profiles"`
	Breakdowns []upgradeBreakdown        `json:"breakdowns"`
}

func loadUpgradeVectors(t *testing.T) upgradeVectors {
	t.Helper()
	var data upgradeVectors
	if err := json.Unmarshal(minerPassUpgradeVectors, &data); err != nil {
		t.Fatal(err)
	}
	if data.Schema != "miner-pass-upgrade-economic-queries:v1" || len(data.Profiles) != 13 || len(data.Breakdowns) != 13 {
		t.Fatal("incomplete upgrade vectors")
	}
	artifact := btcActivationGoldenArtifact{SchemaVersion: goScopedActivationGoldenSchemaVersion, SourceRegistrySchemaVersion: btcActivationRegistrySchemaV3, Registries: []btcActivationRegistry{data.Registry}}
	encoded, err := json.Marshal(artifact)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = parseBTCActivationGolden(encoded); err != nil {
		t.Fatal(err)
	}
	return data
}
func selectorForUpgradeView(t *testing.T, view PassEconomicProfileView) ProfileSelectorPayload {
	t.Helper()
	selector, err := NewProfileSelectorPayload(DifficultyPolicyVersionV1, view.ExternalState.BTCHeight, 0, view.ExternalState.SnapshotID, view.ExternalState.SystemStateID, view.Pass.PassID)
	if err != nil {
		t.Fatal(err)
	}
	return *selector
}

// Included by tests in both builds so default binaries reject this exact catalog.
//
//go:embed testdata/miner_pass_live_activation_golden.json
var minerPassServiceTestGolden []byte

func loadMinerPassServiceRegistry(t *testing.T) btcActivationRegistry {
	t.Helper()
	var artifact btcActivationGoldenArtifact
	if err := json.Unmarshal(minerPassServiceTestGolden, &artifact); err != nil {
		t.Fatal(err)
	}
	if _, err := parseBTCActivationGolden(minerPassServiceTestGolden); err != nil {
		t.Fatal(err)
	}
	if len(artifact.Registries) != 1 || len(artifact.Registries[0].Activations) != 7 {
		t.Fatal("incomplete live service activation schedule")
	}
	return artifact.Registries[0]
}
